master:  
slave: 
ip_master: 
ip_slave: 

path_update_ansible: "{{ path_home_m }}/Kalganaff/roles/win/files/{{ client }}/"
path_ansible_files: "{{ path_home_m }}/Kalganaff/roles/win/files"
# mast vars
path_home_m: "/home/{{ master }}"
#lin vars
path_home: "/home/{{ slave }}/preparation"
#path lin new
path_client: "{{ path_home }}/{{ client }}"
path_update_linux: "{{ path_client }}/update"
path_update_lib: "{{ path_update_linux }}/lib"
#path lin old
path_prog_lib: "{{ path_prog }}/lib"
path_prog:  "{{ path_client }}/prog"
#path lin create windows

#path java version
path_java: "{{ path_prog }}/jre/work/"
#path verifon

#path sber

#win vars
path_home_win: "C:\\{{ client }}"
path_sborka: "C:\\client\\sborka"
path_sborka_ps: "{{ path_sborka }}\\start_pr.ps1"
path_create: "{{ path_sborka }}\\create_windows\\"
path_file_nsis: "{{ path_create }}\\Installers\\tpo\\20200806"
path_nsis: "{{ path_file_nsis }}\\{{ client }}.nsi"
path_win_prog: "{{ path_file_nsis }}\\prog\\"
path_makensisw: "{{ path_create }}\\NSIS\\makensisw.exe"
