master: user 
slave: andrey

path_home: "/home/{{ slave }}/"
path_client: "{{ path_home }}/{{ client }}/"
path_update_linux: "{{ path_client }}/update/"
path_update_ansible: "/etc/ansible/roles/win/files/{{ client }}_v5/"
path_ansible_files: "/etc/ansible/roles/win/files/"
path_update_lib: "{{ path_update_linux }}/{{ client }}_v5/lib/"
path_prog_lib: "{{ path_client }}/prog/{{ client }}_v5/lib/"
path_prog:  "{{ path_client }}/prog/"
path_home_win: "C:\\{{ client }}"
path_sborka: "C:\\client\\sborka"
path_sborka_ps: "{{ path_sborka }}\\start_pr.ps1"
path_create: "{{ path_sborka }}\\create_windows\\"
path_file_nsis: "{{ path_create }}\\Installers\\tpo\\20200806"
path_nsis: "{{ path_file_nsis }}\\{{ client }}.nsi"
path_win_prog: "{{ path_file_nsis }}\\prog\\"
path_makensisw: "{{ path_create }}\\NSIS\\makensisw.exe"
