- hosts: all
  vars_prompt:

    - name: client
      prompt: Введи название клиента пример "123"
      private: no

    - name: java
      prompt: Нужно добавлять java? y/n
      private: no

    - name: arh
      prompt: Какая нужна битность? 32 или 64
      private: no

    - name: ver
      prompt: Введи номер версии например - 111
      private: no


  roles:
    - win 
