
- name: Create dir name client and update
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ path_client }}"
    - "{{ path_update_linux }}"


- name: Copy script file search
  template:
    src: file-search.sh.j2
    dest: "{{ path_client }}/file-search.sh"
    mode: '0755'


- import_tasks: files.yml


- name:  формируем список, удаляем и заменяем файлы
  shell: "{{ path_client }}/file-search.sh"
  

