
- name: создаем папки
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ path_client }}"
    - "{{ path_update_linux }}"


- name: Копируем обновление
  shell: scp -r root@192.168.0.100:"{{ path_update_ansible }}" "{{ path_update_linux }}"


- name: Копируем сборщик
  shell: scp -r root@192.168.0.100:"{{ path_ansible_files }}"/create_windows "{{ path_client }}"


#- name: Копируем общий сборщик
 # copy:
  #  src: emanat_v5 
   # dest: "{{ path_update_linux }}"


#- name: Копируем общий сборщик
#  copy:
#    src:  create_windows
#    dest: "{{ path_client }}"


- name: Копируем обновление
  template:
    src: file-search.sh.j2
    dest: "{{ path_client }}/file-search.sh"
    mode: '0755'


- name:  формируем список, удаляем и заменяем файлы
  shell: "{{ path_client }}/file-search.sh"
  

