---

#- name: client name
#  prompt: Specify the name of the client, for example (emanat)
#  private: no


- import_tasks: linux.yml
  when: ansible_distribution == 'Debian'

- import_tasks: win.yml
  when: ((ansible_distribution != 'Debian') or (ansible_distribution != 'RedHate'))
# tasks file for win
#- name: Копируем обновления на линуху все будем делать там
#  copy:
#    src: "{{ item }}"
#    dest: /home/andrey/
#  with_items:
#    - emanat_v5
#    - file-search.sh
#  when: ansible_distribution == 'Debian' 

#- name: Запускаем скрипт скана обновлений 
#  ansible.builtin.script: file-search.sh
#  when: ansible_distribution == 'Debian' 
  

#- name: Отправляем файл смерти и обновление на удаленный комп
#  ansible.windows.win_copy:
#    src: "{{ item }}"
#    dest: C:\eManat\
#  with_items:
#    - start_pr.ps1



#- name: Copy a single file
#  win_file:
#    path: C:\eManat "{{ item }}"
#    state: absent
#  with_items:
#    - test*

#- name: Run multi-lined shell commands
#  ansible.windows.win_shell: |
#    $value = Test-Path -Path C:\eManat
#    if ($value) {
#        Remove-Item -Path C:\eManat -Force
#    }
#    New-Item -Path C:\eManat -ItemType Directory

#- name: Execute a command in the remote shell, stdout goes to the specified file on the remote
#  ansible.windows.win_shell: Remove-Item C:\eManat\test*


