- name: Папку под скрипт и сборщик
  win_file: 
    path: C:\client
    state: directory


- name: Папку под скрипт и сборщик
  win_file:
    path: "{{ path_sborka }}"
    state: directory


- name: Закидываем сборщик
  ansible.windows.win_copy:
    src: "{{ item }}"
    dest: "{{ path_sborka }}"
  with_items:
    - create_windows


- name: Отправляем скрипт сборки
  template:
    src: "{{ item }}"
    dest: "{{ path_sborka_ps }}"
  with_items:
    - start_pr.ps1.j2


- name: Отправляем файл сборки
  ansible.windows.win_copy:
    src: "{{ item }}"
    dest:  "{{ path_file_nsis }}"
  with_items:
    - "{{ client }}.nsi"


- name: Запускаем скрипт сборки
  ansible.windows.win_shell: "{{ path_sborka_ps }}" 

