# This is a basic workflow to help you get started with Actions

name: CI-CD-test
env: 
  DEPLOY_PACKAGE_NAME: "ansible-roles_${{ github.sha }}.zip"
  
on:
  push:
    branches: 
      - main

jobs:
  my_ci_part:
    runs-on: ubuntu-latest
    
    steps: 
    - name: hello
      run:
        echo "Hello message"

    - name: check dir
      run:  ls -la
        
    - name: git clone repo
      uses: actions/checkout@v1
      
    - name: Create Zip deployment package
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git* 

    - name: check dir
      run:  ls -la
      
    - name: check ansible
      run: ansible --version
      
    - name: check syntax yml
      run: ansible-playbook win.yml --check
      
    - name: ping my server
      run: ping-n 3 192.168.0.50
